<a href="https://colab.research.google.com/github/vsnaveen1/MyTensorFlow/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundas of Tensors, using Tensor flow

* Intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors & Numpy
* using @tf.function
* Using GPUs with Tesnsor flow




In [1]:
## Intro to Tensors

In [6]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.11.0


In [7]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

# check the number of dimensions of a tensor (ndim stands for number of dimensions

In [8]:
scalar.ndim

0

In [9]:
# create a vector?
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
#dimenstions
vector.ndim

1

In [11]:
# create a matrix that has more than one dimensions
matrix = tf.constant([[0.1,1],[22,2.2222]])
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.1   ,  1.    ],
       [22.    ,  2.2222]], dtype=float32)>

In [12]:
matrix.ndim


2

In [13]:
# create matrix
another_matrix = tf.constant([[1.,2.],[3.4,3],[4.,5]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1. , 2. ],
       [3.4, 3. ],
       [4. , 5. ]], dtype=float16)>

In [14]:
another_matrix.ndim

2

In [15]:
tensor = tf.constant([[[1,3,3],[4,5,5],[4,5,4]],
                      [[1,3,3],[4,5,5],[4,5,4]],
                      [[1,3,3],[4,5,5],[4,5,4]]])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 3, 3],
        [4, 5, 5],
        [4, 5, 4]],

       [[1, 3, 3],
        [4, 5, 5],
        [4, 5, 4]],

       [[1, 3, 3],
        [4, 5, 5],
        [4, 5, 4]]], dtype=int32)>

In [16]:
tensor.ndim

3

What we created so far

* Scalar:  a single number 0 dimensions
* Vector: a number with direction ( wind speed and direction, velocity)
* Matrix : a 2 dimensional array of numbers
* Tensor : an n-dimensional array of numbers, scalar is a 0- ranked, 0-dimensioned Tensor, a vector is 1 ranked, 1-dimensioned tensor, 2- dimenstional tensor is a matrix, 

In [17]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
# lets change changeable tensor
changeable_tensor[0]=22
changeable_tensor

TypeError: ignored

In [20]:
# lets try assign
changeable_tensor[0].assign(87)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([87,  7], dtype=int32)>

In [22]:
# Lets try changing the constant
unchangeable_tensor[0].assign(55)
unchangeable_tensor

AttributeError: ignored

In [23]:
# creating random tensor
# Random tensors are tensors of some arbitrary size with random numbers
random_tf_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_tf_1=random_tf_1.normal(shape=(3,2))
random_tf_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [24]:
random_tf_2 = tf.random.Generator.from_seed(42)
random_tf_2
random_tf_2 = random_tf_2.normal(shape=(3,2))

random_tf_2, random_tf_1==random_tf_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elements in a tensor


In [25]:
# Shuffle the order of elements in a tensor
# shuffle a tensor (valuale when you want to shuffle your data, so it doesnt effect your learning)
not_shuffled = tf.constant([[10,7],[3,5],[5,3]])
not_shuffled.ndim

#shuffle the non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 5,  3]], dtype=int32)>

In [26]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 5,  3]], dtype=int32)>

In [27]:
random_tf_3 = tf.random.Generator.from_seed(42)
random_tf_3

In [28]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)
# if we want our shuffled tensors to be in the same order, we have to use global level and operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 5,  3]], dtype=int32)>

# Other way to make tensors using numpy

In [29]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [30]:
#Create tensors with all zeros

tf.zeros([2,3])
#or
tf.zeros(shape=(2,33))

<tf.Tensor: shape=(2, 33), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]], dtype=float32)>

#### NumPy arrays vs Tensorflow tensors 
Tensors can be run on a GPU computing

In [31]:
# you can also turn numPy arrays into tensors
import numpy as np
numpy_A= np.arange(1,25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

#X= tf.constant(some_matrix) # capital for matrix or tensor
#y =tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [32]:
A = tf.constant(numpy_A)
B=tf.constant(numpy_A,shape=(2,12))
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

##### Getting more info from tensors

* Shape
* Rank
* Axis or dimesniton
* Size


In [33]:
# Create a rank 4 tensor (4 dimensions)
rank4tensor = tf.zeros(shape=[2,3,4,5])
rank4tensor[0],rank4tensor.shape, rank4tensor.ndim,tf.size(rank4tensor)

(<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>,
 TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
# Beautify
print("Datatype of every element", rank4tensor.dtype)
print("Number of dimensions (rank)", rank4tensor.ndim)
print("shape of tensor", rank4tensor.shape)
print("elements along 0 axis", rank4tensor.shape[0])
print("elements along last axis", rank4tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank4tensor).numpy())

Datatype of every element <dtype: 'float32'>
Number of dimensions (rank) 4
shape of tensor (2, 3, 4, 5)
elements along 0 axis 2
elements along last axis 5
Total number of elements in our tensor 120


### Indexing tensors
Tensors can be indexed just like python lists

In [35]:
# Get first 2 elements of each dimensions

rank4tensor[:2,:4,:2,:2]

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
# Get first element from each dimension from each index except for the final one
rank4tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# create a rank 2 tensor
rank2tensor = tf.constant([[2,3],[5,6],[55,666]])
rank2tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  2,   3],
       [  5,   6],
       [ 55, 666]], dtype=int32)>

In [38]:
# get last item of each row of rank2 tensor.
rank2tensor[:,-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  3,   6, 666], dtype=int32)>

In [39]:
rank3tensor =rank2tensor[...,tf.newaxis]
rank3tensor

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[  2],
        [  3]],

       [[  5],
        [  6]],

       [[ 55],
        [666]]], dtype=int32)>

In [40]:
# Alternative to new axis
tf.expand_dims(rank2tensor,axis=rank2tensor.ndim)

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[  2],
        [  3]],

       [[  5],
        [  6]],

       [[ 55],
        [666]]], dtype=int32)>

#### manipulating tensors (tensor operations)

In [41]:
# you can add using operators
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [42]:
#Multiply
tensor*22

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 154],
       [ 66,  88]], dtype=int32)>

In [43]:
tensor[:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

#### In ML Matrix multiplication is pretty common thing

In [44]:
# matrix multiplications in tensor flow
tensor1=tf.constant([[1,3],[2,2],[33,2],[33,22]])
#tf.multiply(tensor,tensor1 )
#tensor @ tensor1 # wont work
tensor1 @ tensor # will work

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 19,  19],
       [ 26,  22],
       [336, 239],
       [396, 319]], dtype=int32)>

1. Inner dimensions must match
2. The resulting matrix has same shape as outer dimension
3. New size is outside numbers [m,n] @[n,o] will result in [m,o]

In [45]:
tensor1=tf.reshape(tensor1,shape=(2,4))
tensor @ tensor1
#tensor1

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[241,  44, 251, 174],
       [135,  17, 138,  94]], dtype=int32)>

In [46]:
# perform the dot product on X and Y ( X or Y transpose)

tf.tensordot(tf.transpose(tensor),tensor1, axes =1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[109,  36, 119,  86],
       [139,  29, 146, 102]], dtype=int32)>

In [47]:
tf.tensordot(tensor,tf.reshape(tensor1,shape=(2,4)), axes =1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[241,  44, 251, 174],
       [135,  17, 138,  94]], dtype=int32)>

In [48]:
print ("Normal tensor");
print (tensor1);
print ("/n reshaped");
print (tf.reshape(tensor1, shape=(4,2)))
print("/n transposed")

print(tf.transpose(tensor1))

Normal tensor
tf.Tensor(
[[ 1  3  2  2]
 [33  2 33 22]], shape=(2, 4), dtype=int32)
/n reshaped
tf.Tensor(
[[ 1  3]
 [ 2  2]
 [33  2]
 [33 22]], shape=(4, 2), dtype=int32)
/n transposed
tf.Tensor(
[[ 1 33]
 [ 3  2]
 [ 2 33]
 [ 2 22]], shape=(4, 2), dtype=int32)


#### Changing data type of the tensor

In [49]:
# Create a new tensor with default data type
B = tf.constant([1.7,5.4])
C= tf.constant([4,5])
B.dtype
C.dtype

tf.int32

In [50]:
## changing float 32 to 16, its called reducing precision

D = tf.cast(B,dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 5.4], dtype=float16)>,
 tf.float16)

In [51]:
# change from int 32 to float16
E = tf.cast(C,tf.float16)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([4., 5.], dtype=float16)>,
 tf.float16)

#### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [52]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [53]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms Of Aggregations
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [54]:
# Creating a random tensor
E = tf.constant(np.random.randint(0,100, size =50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([78, 40,  0, 91, 99, 89, 36, 12, 48, 71,  0, 15, 66, 75, 79, 33,  1,
       50, 21, 58, 71, 97, 15, 45,  4, 95, 87, 24,  0,  3, 50, 81, 86,  4,
        4, 62, 24, 17, 15, 69, 87, 95, 92, 15, 56, 27, 81, 76, 52, 45])>

In [55]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [56]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [57]:
# find max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [58]:
#find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2441>

In [59]:
#find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [60]:
#find the standard deviance
E=tf.cast(E,np.float16);
tf.math.reduce_std(E,0)

<tf.Tensor: shape=(), dtype=float16, numpy=32.7>

In [61]:
#find the variance of our tensor, we need tensorflow_probability
import tensorflow_probability as tfp 
tfp.stats.variance(E),tf.math.reduce_variance(E)

(<tf.Tensor: shape=(), dtype=float16, numpy=1069.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=1069.0>)

*** find the positional max and minimum

In [62]:
tf.argmax(E),tf.argmin(E),tf.argsort(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([ 2, 10, 28, 16, 29, 24, 33, 34,  7, 11, 22, 38, 43, 37, 18, 27, 36,
        45, 15,  6,  1, 23, 49,  8, 17, 30, 48, 44, 19, 35, 12, 39,  9, 20,
        13, 47,  0, 14, 31, 46, 32, 26, 40,  5,  3, 42, 25, 41, 21,  4],
       dtype=int32)>)

In [63]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F,tf.argmax(F),tf.argmin(F),tf.argsort(F)


(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([16,  4, 43, 22, 12, 47, 19, 27, 35,  9,  8, 31, 40, 38, 10, 49, 25,
         2, 29,  1,  3, 34, 17,

#### Squeezing tensors (removing all single dimensions)

In [64]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [65]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [66]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

##### One Hot encoding is a numerical encoding

In [67]:
# Create a list of indices
some_list = [0,1,2,3]  # red, green, blue, purple

# one hot encode our list of indices
tf.one_hot(some_list, depth=40)


<tf.Tensor: shape=(4, 40), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [68]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="hu",off_value="ho")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hu', b'ho', b'ho', b'ho'],
       [b'ho', b'hu', b'ho', b'ho'],
       [b'ho', b'ho', b'hu', b'ho'],
       [b'ho', b'ho', b'ho', b'hu']], dtype=object)>

In [69]:
#### squaring, log, square root
H = tf.range(1,10)
#H
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [70]:
I = tf.cast(H,tf.float32)
tf.sqrt(I)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [71]:
tf.math.log(I)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#### Tensors and numpy

In [72]:
# Create a tensor directly from numpy
J = tf.constant(np.array([.3,.7,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 0.3,  0.7, 10. ])>

In [73]:
# Convert tensor to numpy
np.array(J),type(np.array(J))

(array([ 0.3,  0.7, 10. ]), numpy.ndarray)

In [74]:
J.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 0.3,  0.7, 10. ])>>

In [75]:
J=tf.constant([3.])
J.numpy()[0]

3.0

In [80]:
#Default types of each are different
numpy_J= tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

In [77]:
#### Finding Access to GPU
tf.test.is_gpu_available

<function tensorflow.python.framework.test_util.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None)>

In [79]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [81]:
!nvidia-smi

Tue Mar 14 18:18:25 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0    28W /  70W |    335MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

:If you have access to a CUDA enabled GPU, Tensorflow will automatically use it whenever possible\